---
title: "exam_wk4_inequalitymap"
author: "Siyuan"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include=FALSE)
```

## install 'countrycode' package

```{r include=FALSE}
install.packages("countrycode")
```

## read data

```{r}
library(here)
library(sf)

inequal_2010 <- read.csv(here('exam_wk4', 'raw_data_wk4', 'hdr-data_2010.csv'))
# 老师增加：locale = local(encoding = 'latin1'), na = '', skip=0)
inequal_2019 <- read.csv(here('exam_wk4', 'raw_data_wk4', 'hdr-data_2019.csv'))
shp_path <- here('exam_wk4', 'raw_data_wk4', 
                       'World_Countries_(Generalized)_2402777631520798174',
                       'World_Countries_Generalized.shp')
worldmap <- st_read(shp_path)

# head(inequal_2010)
# head(worldmap)
```

## delete unnecessary data from csv.

```{r}
library(dplyr)

onlyineq_2010 <- inequal_2010 %>% 
  filter(index == 'Gender Inequality Index', 
         indicator == 'Gender Inequality Index (value)') %>%
  # select(-note)

onlyineq_2019 <- inequal_2019 %>% 
  filter(index == 'Gender Inequality Index', 
         indicator == 'Gender Inequality Index (value)') %>%
  # select(-note)

write.csv(onlyineq_2010, here('exam_wk4', 
                              'raw_data_wk4', 
                              'onlyinequal_2010.csv'), 
          row.names = FALSE)
write.csv(onlyineq_2019, here('exam_wk4', 
                              'raw_data_wk4', 
                              'onlyinequal_2019.csv'), 
          row.names = FALSE)
head(onlyineq_2010)
```

## add *difference btw 2010&2019* and *newISO* into csv.

```{r}
library(countrycode)

onlyineq_2010 <- onlyineq_2010 %>%
  left_join(onlyineq_2019 %>% select(countryIsoCode, value), 
            by = 'countryIsoCode',
            suffix = c('', '_2019')) %>%
  mutate(value_2019 = value_2019) 

onlyineq_2010 <- onlyineq_2010 %>%
  mutate(differ = round(value_2019 - value, 3))

onlyineq_2010 <- onlyineq_2010 %>%
  mutate(newISO = countrycode(countryIsoCode, 
                              origin = 'iso3c', destination = 'iso2c'))
```

## merge csv. and shp by ISO 注意不要根据字符串匹配，人们写文字的习惯不一样（e.g. University of AAA v.s. AAA University

```{r}
ineqmap <- worldmap %>%
  left_join(onlyineq_2010 %>% select(newISO, differ), 
            by = c('ISO' = 'newISO')) 
head(ineqmap)
```

## plot

```{r}
library(ggplot2)

ggplot(data = ineqmap) +
  geom_sf(aes(fill = differ), color = "black") +  # fill color by 'differ'
  scale_fill_gradient(low = "darkblue", high = "lightblue", na.value = "grey50") + 
  labs(title = "Difference in Gender Inequality Index (2019 - 2010)",
       fill = "Difference") + 
  theme_minimal() +  # 使用简约主题
  theme(plot.title = element_text(hjust = 0.5)) 
```

